# ----------------------------
# Makefile Options
# ----------------------------

NAME = Nunchuck
DESCRIPTION = "Nunchuck Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz
LDHAS_EXIT_HANDLER:=0
# ----------------------------

include $(shell cedev-config --makefile)
